Repository canonical/greenhouse-browser-scripts, pull requests merged in 2023-05, with the labels that each got.

#37 Add new URL match rule for written-interview-in-new-tab.user.js
  written-interview-in-new-tab.user.js
Labels: Review: Code +1

#38 Add tests and Github actions (WD-2828)
  .github/workflows/pr.yaml
  __tests__/application-review-helper.test.js
  __tests__/application-review.test.js
  __tests__/written-interview-in-new-tab.test.js
  babel.config.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  yarn.lock
Labels: Review: Code +1 (with changes), Review: QA +1

#40 WD-3825 Replace Wrong timezone with Jumpy career
  application-review.user.js
Labels: Review: Code +1, Review: QA +1

#39 WD-3819 Replace ariaLabel with getAttribute("aria-label")
  application-review.user.js
Labels: Review: Code +1, Review: QA +1

#41 Bump the version to 1.1.0
  application-review.user.js
Labels: Review: Code +1
